name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format_and_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cargo fmt
      run: cargo fmt --all -- --check
    - name: Cargo doc
      run: cargo doc

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all
      run: cargo build --release
    - name: Run unit tests and doctests
      run: cargo test --release
    - name: Run test harness
      run: cd test_harness && cargo run --release -- -v

